### PR TITLE
Adding Mixins for Trix Editor Events

### PR DESCRIPTION
**Pull request by isocroft**
This PR proposes to add 3 events of the **trix editor** as mixins:

- trixInitialize
- trixBeforeInitialize
- trixSelectionChange

As they are important for setup up bootstrap code (boilerplate) for initializing the editor differently as one prefers

### CODE REVIEW

**Comment by isocroft** [comment]
I might need to update the README with commits later on if you accent to this PR

**Comment by hanhdt** [comment]
Hi @isocroft ,
Thank you for suggesting PR.
I would like to cherry-pick up them. And it would be nice since you update README too.

**Comment by isocroft** [comment]
Alright

**Comment by hanhdt** [comment]
After reviewed your PR, it is a little bit confused. Where did you fire these events from main component?

**Comment by isocroft** [comment]
Yeah... my mistake i was supposed to do that but i forgot. Will send a follow up PR

**Pull request merged**
